/**
 * Known-answer tests against code/crypto/test_vectors.json, generated by the
 * authoritative Python implementation. CI fails if the two disagree.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { aesGcmDecrypt, aesGcmEncrypt } from "./aes";
import {
  bytesToHex,
  hexToBytes,
  makeShare,
  shareFromBytes,
  shareFromText,
  shareToBytes,
  shareToText,
} from "./encoding";
import { unwrapWithPrivateKey } from "./rsa";
import { PRIME, reconstructSecret, splitWithCoefficients } from "./shamir";

const vectors = JSON.parse(
  readFileSync(new URL("../../../code/crypto/test_vectors.json", import.meta.url), "utf8"),
);
const hexInt = (h: string) => BigInt("0x" + h);

export const matched = { shamir: 0, aes: 0, rsa: 0 };

describe("test vectors (Python <-> TypeScript)", () => {
  it("uses the same field", () => {
    expect(vectors.version).toBe(1);
    expect(hexInt(vectors.field.prime_hex)).toBe(PRIME);
  });

  for (const c of vectors.shamir) {
    it(`shamir: ${c.name}`, () => {
      const shares = splitWithCoefficients(c.coefficients_hex.map(hexInt), c.n);
      shares.forEach((share, i) => {
        const v = c.shares[i];
        expect(share).toEqual(makeShare(v.x, hexInt(v.y_hex)));
        expect(bytesToHex(shareToBytes(share))).toBe(v.bytes_hex);
        expect(shareToText(share)).toBe(v.text);
        expect(shareFromText(v.text)).toEqual(share);
        expect(shareFromBytes(hexToBytes(v.bytes_hex))).toEqual(share);
      });
      const byX = new Map(shares.map((s) => [s.x, s]));
      for (const r of c.reconstructions) {
        expect(reconstructSecret(r.xs.map((x: number) => byX.get(x)!))).toBe(hexInt(r.secret_hex));
        expect(hexInt(r.secret_hex)).toBe(hexInt(c.secret_hex));
      }
      for (const r of c.insufficient) {
        const value = reconstructSecret(r.xs.map((x: number) => byX.get(x)!));
        expect(value).toBe(hexInt(r.value_hex));
        expect(value === hexInt(c.secret_hex)).toBe(false);
      }
      matched.shamir++;
    });
  }

  for (const c of vectors.aes_gcm) {
    it(`aes-gcm: ${c.name}`, async () => {
      const [key, iv, aad, pt] = [c.key_hex, c.iv_hex, c.aad_hex, c.plaintext_hex].map(hexToBytes);
      expect(bytesToHex(await aesGcmEncrypt(key, iv, pt, aad))).toBe(c.ciphertext_hex);
      expect(bytesToHex(await aesGcmDecrypt(key, iv, hexToBytes(c.ciphertext_hex), aad))).toBe(c.plaintext_hex);
      matched.aes++;
    });
  }

  const rsa = vectors.rsa_oaep[0];
  for (const c of rsa.cases) {
    it(`rsa-oaep: ${c.name}`, async () => {
      const plaintext = await unwrapWithPrivateKey(rsa.private_jwk, hexToBytes(c.ciphertext_hex));
      expect(bytesToHex(plaintext)).toBe(c.plaintext_hex);
      matched.rsa++;
    });
  }
});
